### ISSUE TITLE
[Question] Example to fit a training dummy?

### ISSUE THREAD

**Issue by himpich** [JereKuusela/valheim-world_edit_commands#12]
In the documentation you mention "Decorating the training dummy since it never attacks."

I tried (several combinations of): `spawn_object TrainingDummy chest=ArmorBronzeChest` but still get "a normal dummy". Could you please provide one or two examples for spawning such dummies, e.g. with armor and a weapon? This would be great, thanks!

**Comment by JereKuusela** [comment]
It depends on the object which slots are available. For example training dummy only has helmet, left hand and right hand.

**Comment by himpich** [comment]
thanks a lot!
