### ISSUE TITLE
durability parameter does not work anymore on existing objects (health does)

### ISSUE THREAD

**Issue by himpich** [JereKuusela/valheim-world_edit_commands#13]
in the past I could create "unbreakable" oaks via e.g. `object id=woodwall radius=20 durability=1E30`

now the oaks have default durability. Using `object id=woodwall radius=20 health=1E30` still works

I also can now change the health of a hovered object, e.g. 
![image](https://user-images.githubusercontent.com/6817957/190255067-c175cf41-f3e9-46e6-a06a-4c3fb7fd7d13.png)
I am not sure if this worked in the past.

spawning creature and setting durability aka health still works

**Comment by JereKuusela** [comment]
Durability and health are the same operations but looks like durability was missing from the allowed operations. I will add it back for the next version.

Thanks foir the report!
